#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidSample.Resource", IsApplication=true)]

namespace AndroidSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::UnviredMonoDroidKernel.Resource.Array.domains = global::AndroidSample.Resource.Array.domains;
			global::UnviredMonoDroidKernel.Resource.Drawable.logo = global::AndroidSample.Resource.Drawable.logo;
			global::UnviredMonoDroidKernel.Resource.Drawable.Microsoft = global::AndroidSample.Resource.Drawable.Microsoft;
			global::UnviredMonoDroidKernel.Resource.Drawable.unvired = global::AndroidSample.Resource.Drawable.unvired;
			global::UnviredMonoDroidKernel.Resource.Id.CancelButton = global::AndroidSample.Resource.Id.CancelButton;
			global::UnviredMonoDroidKernel.Resource.Id.CompanyLabel = global::AndroidSample.Resource.Id.CompanyLabel;
			global::UnviredMonoDroidKernel.Resource.Id.CompanyTextField = global::AndroidSample.Resource.Id.CompanyTextField;
			global::UnviredMonoDroidKernel.Resource.Id.DomainLabel = global::AndroidSample.Resource.Id.DomainLabel;
			global::UnviredMonoDroidKernel.Resource.Id.DomainTextField = global::AndroidSample.Resource.Id.DomainTextField;
			global::UnviredMonoDroidKernel.Resource.Id.FinalURLLabel = global::AndroidSample.Resource.Id.FinalURLLabel;
			global::UnviredMonoDroidKernel.Resource.Id.HeadingLabel = global::AndroidSample.Resource.Id.HeadingLabel;
			global::UnviredMonoDroidKernel.Resource.Id.LoginButton = global::AndroidSample.Resource.Id.LoginButton;
			global::UnviredMonoDroidKernel.Resource.Id.LoginTypeImage = global::AndroidSample.Resource.Id.LoginTypeImage;
			global::UnviredMonoDroidKernel.Resource.Id.OptionsButton = global::AndroidSample.Resource.Id.OptionsButton;
			global::UnviredMonoDroidKernel.Resource.Id.PasswordTextfield = global::AndroidSample.Resource.Id.PasswordTextfield;
			global::UnviredMonoDroidKernel.Resource.Id.URLLabel = global::AndroidSample.Resource.Id.URLLabel;
			global::UnviredMonoDroidKernel.Resource.Id.URLPrefixLabel = global::AndroidSample.Resource.Id.URLPrefixLabel;
			global::UnviredMonoDroidKernel.Resource.Id.URLPrefixSpinner = global::AndroidSample.Resource.Id.URLPrefixSpinner;
			global::UnviredMonoDroidKernel.Resource.Id.URLTextfield = global::AndroidSample.Resource.Id.URLTextfield;
			global::UnviredMonoDroidKernel.Resource.Id.UserNameTextField = global::AndroidSample.Resource.Id.UserNameTextField;
			global::UnviredMonoDroidKernel.Resource.Id.linearLayout1 = global::AndroidSample.Resource.Id.linearLayout1;
			global::UnviredMonoDroidKernel.Resource.Id.linearLayout2 = global::AndroidSample.Resource.Id.linearLayout2;
			global::UnviredMonoDroidKernel.Resource.Id.scroll = global::AndroidSample.Resource.Id.scroll;
			global::UnviredMonoDroidKernel.Resource.Id.textView5 = global::AndroidSample.Resource.Id.textView5;
			global::UnviredMonoDroidKernel.Resource.Id.textView6 = global::AndroidSample.Resource.Id.textView6;
			global::UnviredMonoDroidKernel.Resource.Layout.LoginPage = global::AndroidSample.Resource.Layout.LoginPage;
			global::UnviredMonoDroidKernel.Resource.String.DomainSpinner = global::AndroidSample.Resource.String.DomainSpinner;
			global::UnviredMonoDroidKernel.Resource.String.library_name = global::AndroidSample.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int from_middle = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int left_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int right_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int to_middle = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int domains = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Microsoft = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int search_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splashimage = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int unvired = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090026
			public const int CancelButton = 2131296294;
			
			// aapt resource value: 0x7f09000c
			public const int City = 2131296268;
			
			// aapt resource value: 0x7f090022
			public const int CompanyLabel = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int CompanyTextField = 2131296291;
			
			// aapt resource value: 0x7f090002
			public const int CustomersList = 2131296258;
			
			// aapt resource value: 0x7f09001e
			public const int DomainLabel = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int DomainTextField = 2131296287;
			
			// aapt resource value: 0x7f09001d
			public const int FinalURLLabel = 2131296285;
			
			// aapt resource value: 0x7f090018
			public const int HeadingLabel = 2131296280;
			
			// aapt resource value: 0x7f09000f
			public const int Kunnr = 2131296271;
			
			// aapt resource value: 0x7f090001
			public const int LocalSearchField = 2131296257;
			
			// aapt resource value: 0x7f090025
			public const int LoginButton = 2131296293;
			
			// aapt resource value: 0x7f090017
			public const int LoginTypeImage = 2131296279;
			
			// aapt resource value: 0x7f090006
			public const int Name = 2131296262;
			
			// aapt resource value: 0x7f090028
			public const int NameTextField = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int NumberTextField = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int OnlineSearchButton = 2131296298;
			
			// aapt resource value: 0x7f090027
			public const int OptionsButton = 2131296295;
			
			// aapt resource value: 0x7f090021
			public const int PasswordTextfield = 2131296289;
			
			// aapt resource value: 0x7f090012
			public const int Postcode1 = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int Text = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int Text1 = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int Text2 = 2131296277;
			
			// aapt resource value: 0x7f09001b
			public const int URLLabel = 2131296283;
			
			// aapt resource value: 0x7f090019
			public const int URLPrefixLabel = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int URLPrefixSpinner = 2131296282;
			
			// aapt resource value: 0x7f09001c
			public const int URLTextfield = 2131296284;
			
			// aapt resource value: 0x7f090020
			public const int UserNameTextField = 2131296288;
			
			// aapt resource value: 0x7f09002b
			public const int action_search = 2131296299;
			
			// aapt resource value: 0x7f090003
			public const int linearLayout1 = 2131296259;
			
			// aapt resource value: 0x7f090024
			public const int linearLayout2 = 2131296292;
			
			// aapt resource value: 0x7f090004
			public const int linearLayout3 = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout4 = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int linearLayout5 = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int linearLayout6 = 2131296269;
			
			// aapt resource value: 0x7f090010
			public const int linearLayout7 = 2131296272;
			
			// aapt resource value: 0x7f090000
			public const int linearLayoutsearch = 2131296256;
			
			// aapt resource value: 0x7f090016
			public const int scroll = 2131296278;
			
			// aapt resource value: 0x7f090009
			public const int street = 2131296265;
			
			// aapt resource value: 0x7f090005
			public const int textView2 = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int textView3 = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int textView4 = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int textView5 = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int textView6 = 2131296273;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AppScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomerDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int OnlineSearch = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int AppActivityActions = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int DomainSpinner = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int library_name = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
